name: "Go Extract Code"
description: "Extracts code blocks from a BUILD.md file."
inputs:
  build_file:
    description: "Path to the BUILD.md file."
    required: true
    default: "scripts/BUILD.md"
  output_dir:
    description: "Output directory for generated files."
    required: true
    default: "generated_code"
  verbose:
    description: "Enable verbose output."
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'  # Adjust as needed
    - name: Install Dependencies
      run: go mod tidy
    - name: Build and Run
      run: |
        go build -o go_extract_code ./cli.go ./main.go
        ./go_extract_code -build=${{ inputs.build_file }} -out=${{ inputs.output_dir }} -v=${{ inputs.verbose }}