name: Go Tests and Linting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      # Step 3: Install golangci-lint
      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.54.2

      # Step 4: Run golangci-lint with the configuration file
      - name: Run golangci-lint
        run: golangci-lint run --config .golangci.yml

      # Step 5: Install Dependencies
      - name: Install Dependencies
        run: go mod tidy

      # Step 6: Run Go tests
      - name: Run Tests
        run: go test -v ./...